### ISSUE TITLE
E/CycledLeScannerForLollipop(15802): Scan failed: app cannot be registered

### ISSUE THREAD

**Issue by thangtq-intelads** [alann-maulana/flutter_beacon#12]
sometime i have an error "E/CycledLeScannerForLollipop(15802): Scan failed: app cannot be registered" and then i can't use my phone to detect any beacon but i still use location service like google map application.

i try to "google" and i find the similar issues as bellow, please help me to resolve it
https://github.com/AltBeacon/android-beacon-library/issues/694

**Comment by alann-maulana** [comment]
Hi @thangtq-intelads 

What device manufacture and type do use for scanning? Well, as you know I'm using [Android Beacon Library](https://github.com/AltBeacon/android-beacon-library) for manage scanning in Android. Please try to upgrade the library by using the latest [here](https://github.com/AltBeacon/android-beacon-library/releases).

**Comment by thangtq-intelads** [comment]
thanks for your support

**Comment by alann-maulana** [comment]
Already updated to the latest Android Beacon Library, you can update it using [v0.2.2](https://pub.dartlang.org/packages/flutter_beacon/versions/0.2.2). I hope it can fix the problems :D
