### ISSUE TITLE
Put major in a variable 

### ISSUE THREAD

**Issue by MelissaCOURLA** [alann-maulana/flutter_beacon#13]
Hi, I try to create a variable   like this final _major = result.beacons[<index of desired beacon>].major but I don't understand what is an index of desired beacon. 
I try this line final _major = result.beacons[<beacon>].major 
I try add this line  with other variable
class _MyAppState extends State<MyApp> 
{
  StreamSubscription<RangingResult> _streamRanging;
  final _beacons = <Beacon>[];
  final _major = result.beacons[<Beacon>].major;
....
} but there are an issue with result which does not existe
I try add my line in 
_streamRanging = flutterBeacon.ranging(regions).listen
      ((result) 
        {
          result.beacons.forEach
          ((b) 
            {
              final _major = result.beacons[<Beacon>].major;
              print(b.major);
              _beacons.sort(_compareParameters); 
              monid =b.major;
              print('monid=');
              print(monid);
             return b.major;
            }
         );
        }
      ); with this code the issue is "The argument type 'List<Beacon>' can't be assigned to the parameter type 'int'"
my goal it's take the major and put it in a variable. But I am a beginner in flutter , can you help please

**Comment by alann-maulana** [comment]
Hi @MelissaCOURLA 

For ranging result, `beacons` is a `List` of `Beacon`'s object. You need to learn about how to get data from a list by referring to [List class docs here](https://docs.flutter.io/flutter/dart-core/List-class.html).

**Comment by MelissaCOURLA** [comment]
than for your answer
