### ISSUE TITLE
Not working when ranging beacon

### ISSUE THREAD

**Issue by 1553011** [alann-maulana/flutter_beacon#17]
Using the function Ranging beacon, I got the error like this:  java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager. Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available. I dont know how to fix this issue. Is there anyone know how to solve this problem ?

**Comment by alann-maulana** [comment]
Hi @1553011 

What phone do you use for testing? Android version? I use Sams*ng S5 and S10+ and there are no error happen.

**Comment by dvlj** [comment]
same problem happen with samsung s7 (lastest android os version)

**Comment by Victor-emil** [comment]
I am also getting this exact error. It worked perfectly a month ago, but in the meantime I've updated dart to Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5). When booting up my project this morning I got the error. I'm on a Samsung Galaxy S6.

**Comment by awazgyawali** [comment]
This is not working on Samsung phones. I dug in to check what's the issue, found that it uses this version of the library

`api 'org.altbeacon:android-beacon-library:2.16.1'`

but there is an update on the library available [here](https://github.com/AltBeacon/android-beacon-library/releases/tag/2.16.2) and it mentions a fix on Samsung specific phone.

I have updated the version of the library and created a PR [here](https://github.com/alann-maulana/flutter_beacon/pull/18).

@alann-maulana  Can you merge that?

**Comment by shinyford** [comment]
I believe this is because the package is using an old appcompat library: upgrading it to AndroidX should solve the problem. @alann-maulana, is that something you're looking at doing?

**Comment by alann-maulana** [comment]
Sorry dudes, having a lot of homework last month. Already merge it. I hope it will fix your issue. Close it now :)

**Comment by isaiasmac** [comment]
I was having the same error, for hours trying to find a solution, and the solutions is simple add this to build.gradle

`implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'`

**Comment by alann-maulana** [comment]
Great catch @isaiasmac 

I'll consider adding those line to README within FAQ parts 😄
