### ISSUE TITLE
Ranging/monitoring a beacon when app was terminated

### ISSUE THREAD

**Issue by mahmuttaskiran** [alann-maulana/flutter_beacon#22]
Is it possible to monitor or rang a beacon when app work in background or terminated by the os? I can get monitoring events and ranging events when app is in foreground with this plugin. I tried to show a local notification for a right condition of beacons on background, but I could not.

flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)
 No issues found!

Device
>SM N950F • ce08171822449e08057e • android-arm64 • Android 9 (API 28)

**Comment by alann-maulana** [comment]
Hi @mahmuttaskiran 

Maybe this will work for you [AltBeacon/android-beacon-library#Android O ranging in background issue](https://github.com/AltBeacon/android-beacon-library/issues/771#issuecomment-438609313).
But this behavior (ranging beacons in background) will not work on iOS.

Yup, feel free to send PR 😄

**Comment by modernecotech** [comment]
Could you please post a short example of beacon monitoring when app is not running?

**Comment by mahmuttaskiran** [comment]
Thanks, @alann-maulana. I have written a plugin for ranging and monitoring in the background for Android. On iOS I don't know if it is possible or not, I am not an expert on iOS. I have read some articles for possible iOS implementation but as far as I know, there are some restrictions for background execution especially for ranging.

**Comment by modernecotech** [comment]
is it possible to have beacon monitoring in background, and when a beacon is detected for the app to start in background to do some work (maybe send a notification or whatever). Right now it only works for me when the app is either in foreground or background... but not if the app is not started by user.

**Comment by alann-maulana** [comment]
> Could you please post a short example of beacon monitoring when app is not running?

I use this library daily at all of my office projects. You can use the monitoring beacon method both for background and foreground mode.

**Comment by alann-maulana** [comment]
> Thanks, @alann-maulana. I have written a plugin for ranging and monitoring in the background for Android. On iOS I don't know if it is possible or not, I am not an expert on iOS. I have read some articles for possible iOS implementation but as far as I know, there are some restrictions for background execution especially for ranging.

Nice @mahmuttaskiran 

I have some workaround too for enabling foreground ranging beacons on Android. But as far as I know, in iOS you can only extend it for maximum 3 minutes ranging in background. Here is nice article from David G. Young from RadiusNetworks [Extending Background Ranging on iOS](https://www.radiusnetworks.com/2018-11-19-extending-background-ranging-on-ios).

I using these technique too BTW :)

**Comment by alann-maulana** [comment]
> is it possible to have beacon monitoring in background, and when a beacon is detected for the app to start in background to do some work (maybe send a notification or whatever). Right now it only works for me when the app is either in foreground or background... but not if the app is not started by user.

In Android you can extend your Flutter Application Class using these method [Detecting Beacons After App is Killed](https://altbeacon.github.io/android-beacon-library/resume-after-terminate.html). But, as you know there is always a limitation for iOS 😅
