### ISSUE TITLE
Example project Accuracy/RSSI values can't be acquired on iOS

### ISSUE THREAD

**Issue by atavci** [alann-maulana/flutter_beacon#23]
When I run the example project on iOS devices I can't see the Accuracy or RSSI values of the beacons that have been found. Accuracy is always -1.0. The example runs without any problem on a Galaxy S6 Android device (RSSI can be read correctly) but not on an iPhone 6 Plus or a 6th generation iPad. Any idea what might be causing this or can these values be reached from iOS? I've added a screenshot from the iPad, Thanking you in advance.

Edit: I am using iBeacons which are very similar to the [link](https://tr.aliexpress.com/item/32953981724.html?spm=a2g10.search0104.3.53.328a7a91MxKAs8&transAbTest=ae803_5&ws_ab_test=searchweb0_0%2Csearchweb201602_7_10065_10068_319_10059_10884_317_10887_10696_321_322_10084_453_10083_454_10103_10618_10307_537_536%2Csearchweb201603_52%2CppcSwitch_0&algo_pvid=2c6fa3d8-9959-4304-b030-65c05813ff46&algo_expid=2c6fa3d8-9959-4304-b030-65c05813ff46-8) here.

![IMG_A8456207F40A-1](https://user-images.githubusercontent.com/29902904/65417058-e3d17780-de01-11e9-89e8-08f7bbaacf39.jpeg)

**Comment by alann-maulana** [comment]
Hi @atavci 

What iOS version do you use at your iPhone 6+?

**Comment by atavci** [comment]
iPhone 6+ is at iOS version 12.4.1 and the iPad's version is at 12.4

**Comment by alann-maulana** [comment]
Hi @atavci 

Finally I can borrow some old iPhone 6 with iOS 12.4.1, fetching master branch..running example..and it is running well. Not publishing it yet to pub server.

![Example ranging result](https://i.ibb.co/vmF1xH0/Screen-Shot-2019-10-06-at-09-16-58.png)

Change your dependencies :
from 
```
dependencies:
  flutter_beacon: ^0.2.4
```
to
```
dependencies:
  flutter_beacon: 
    git: https://github.com/alann-maulana/flutter_beacon
```

Hope it can help.

**Comment by atavci** [comment]
Hello again, it looks like the beacons that I used before didn't support your plugin, I've tried with another iBeacon, now it works very well. Thank you for your help.

**Comment by alann-maulana** [comment]
Great, you can send me PR to enable scanning for other beacon protocol device @atavci 
It would be appreciated.
