### ISSUE TITLE
Catch with ios13

### ISSUE THREAD

**Issue by doodii** [alann-maulana/flutter_beacon#25]
flutterBeacon.initializeScanning catch and terminate with ios13. When i by pass this process app can work, But beacon.ranging don't work.

how can i fix it?

Thank you.

**Comment by alann-maulana** [comment]
Hi @doodii 

When you start using this library by executing `flutterBeacon.initializeScanning`, this will check 

- `CBCentralManager.state`, if the state is not `CBManagerStatePoweredOn` then this will throw an [Exception](https://github.com/alann-maulana/flutter_beacon/blob/master/ios/Classes/FlutterBeaconPlugin.m#L227)
- But if your bluetooth is already on, then this will [request for authorization](https://github.com/alann-maulana/flutter_beacon/blob/master/ios/Classes/FlutterBeaconPlugin.m#L211)
- Then if your `CLLocationManage. authorizationStatus` either `kCLAuthorizationStatusDenied` or `kCLAuthorizationStatusRestricted` so it will throw an exception too.

It is better to block it execution with try and catch so you can handle the exception that throw. Hope it helps.

**Comment by alann-maulana** [comment]
Hi @AdnanKazi 

My iPhone 6 stuck at iOS 12, can't upgrade it. Can you please debug and run it at Xcode and then please copy-paste the debug log here?

**Comment by AdnanKazi** [comment]
sure will post it but first i need to know which other permission do i need to add in info.plist file may be the issue is about permission

**Comment by AdnanKazi** [comment]
@alann-maulana I got the solution I haven't put the bluetooth permission in info.plist file

hi @doodii 

just add following line in info.plist file your code will works fine.

`<key>NSBluetoothPeripheralUsageDescription</key>
   <string>need blutooth permission</string>
   <key>NSBluetoothAlwaysUsageDescription</key>
   <string>need blutooth permission.</string>`

**Comment by alann-maulana** [comment]
Great @AdnanKazi 

Thanks for your great information. I think there are new property list regarding Bluetooth usage starting iOS 13 [NSBluetoothAlwaysUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription)

I will add these required privacy on to README documents later.
