### ISSUE TITLE
Unable to run example app

### ISSUE THREAD

**Issue by santhoshraje** [alann-maulana/flutter_beacon#28]
I have installed the plugin as specified on a new project on Android Studio and copied over the example app to my main.dart. Unfortunately I am getting the error below:

`The name BluetoothState isn't a type so it cant be used as a type argument`

at these lines: 

`  final StreamController<BluetoothState> streamController = StreamController();`
`  StreamSubscription<BluetoothState> _streamBluetooth;
`

**Comment by alann-maulana** [comment]
Hi @santhoshraje 

I'm using this library on my daily project, didn't found any issue regarding `BluetoothState`. Can you please send me your example project, so I can help you with it.

Thanks.

**Comment by guiassemany** [comment]
Same here!

I just created a new flutter project, added this dependency and If I try to run the example it, it shows the same error.

**Comment by santhoshraje** [comment]
@guiassemany I think I did the same thing as you. I created a new flutter project, installed the dependencies and copied the code from the example main.dart to my own main.dart and got errors.

But when I download the zip file and run the provided example application, it works flawlessly. I am currently developing using the example application that was provided. 

@alann-maulana unfortunately I deleted the example project, but it was basically just a new project with the dependencies and the code from main.dart.

**Comment by alann-maulana** [comment]
Within `master` branch I do a lot of improvements and some breaking changes that doesn't publish it yet to the pub server. Can you change you `dependencies` if this is work for you?

```
dependencies:
    flutter_beacon:
        git: https://github.com/alann-maulana/flutter_beacon
```
