### ISSUE TITLE
Serial number and battery

### ISSUE THREAD

**Issue by MapiFer** [alann-maulana/flutter_beacon#31]
Hi,

There are any way to have the serial number of a beacon?

There are any way to know how much battery does it have?

I want to send an alert when some beacon is lower in battery.

thanks in advance

**Comment by alann-maulana** [comment]
Hi @MapiFer 

This plugin is intended to scan for beacons that using **iBeacon** protocol nearby.  You can use this great plugin [flutter_blue](https://pub.dev/packages/flutter_blue) for connecting to device peripherals via bluetooth core api.
