### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by cataCostea** [alann-maulana/flutter_beacon#34]
When adding the plugin in pubspec.yaml it downloads without the authorization_status.dart and bluetooth_status.dart. Now it can be used only as a local plugin or in combination with other plugins that provide the necessary for location and bluetooth permissions. Any fix for the missing files soon?

**Comment by alann-maulana** [comment]
Hi @cataCostea 

I don't know about missing files, but you can check [bluetooth_state.dart](https://github.com/alann-maulana/flutter_beacon/blob/master/lib/beacon/bluetooth_state.dart) and [authorization_status.dart](https://github.com/alann-maulana/flutter_beacon/blob/master/lib/beacon/authorization_status.dart) right at the `master` branch.

The last published version at pub server is not the latest. You can install it directly from git with 
```
dependencies:
    flutter_beacon:
        git: https://github.com/alann-maulana/flutter_beacon
```

**Comment by cataCostea** [comment]
Thank you @alann-maulana

**Comment by alann-maulana** [comment]
You're welcome @cataCostea 

Feel free to open a new issue if you find one 😁closing it now
