### ISSUE TITLE
Background Scanning

### ISSUE THREAD

**Issue by f1re** [alann-maulana/flutter_beacon#40]
Hi @alann-maulana,

is there any plan for integrating background monitoring ? 

Thanks Alex

**Comment by alann-maulana** [comment]
Hi @f1re 

There is already a monitoring beacon, see at [https://github.com/alann-maulana/flutter_beacon#monitoring-beacons](https://github.com/alann-maulana/flutter_beacon#monitoring-beacons) that already running pretty well at background mode.

I've been used this little library at my daily projects.

**Comment by f1re** [comment]
Thanks for your quick answer! Indeed it does work in background (at least on android so far) nevertheless the flutter thread crashes after executing e.g. an intent action once an event is detected. Afterwards the monitoring continues running natively, but when trying to communicate with the
flutter thread it fails to communicate with the flutter side obviously. Any idea on that?

**Comment by typexy** [comment]
Hi @alann-maulana is **monitoring** also working on iOs, when app is running in background (but not terminated)?

**Comment by Bhuvan69** [comment]
@typexy Did you find a way to monitor the beacons on background?

**Comment by devberkay** [comment]
is monitoring on iOS in background possible? I couldn't do that.
