### ISSUE TITLE
Scanning frequency

### ISSUE THREAD

**Issue by luisestudioalfa** [alann-maulana/flutter_beacon#44]
Hi,

Is possible to modify de scanning frequency? the beacons that i'm using can advertise with faster intervals (100ms, 200ms, and so on). Is posible to modify the frequency at which the app does the scan so i can get more measurements?

Thank you!

**Comment by alann-maulana** [comment]
Hi @luisestudioalfa 

Yes it is possible, for Android. But not for iOS.

Android Beacon Library make it possible to change for both [foreground](https://altbeacon.github.io/android-beacon-library/javadoc/reference/org/altbeacon/beacon/BeaconManager.html#setForegroundBetweenScanPeriod(long)) and [background](https://altbeacon.github.io/android-beacon-library/javadoc/reference/org/altbeacon/beacon/BeaconManager.html#setBackgroundScanPeriod(long)) scan interval. You can send me a PR to add these functionality
