### ISSUE TITLE
Beacon Info when Monitoring 

### ISSUE THREAD

**Issue by dariocavada** [alann-maulana/flutter_beacon#48]
Would be useful to obtain the beacon Info when I use monitoring feature.
In the result I've
- type
- status
- region (the region identifier and proximityUUID)

I need also major and minor info to understand What beacon is calling me (Like in Ranging feature).

**Comment by santhoshraje** [comment]
Good idea. I'm using ranging right now only because it gives me the major and minor of the beacon and monitoring does not.

**Comment by dariocavada** [comment]
Would be good, but I think is a limitation of the underlying API.

Probably the correct approach is:
1) activate **monitoring** to see if there are beacons with that UUID
2) when there is some beacon, activate the **ranging** to understand which beacon it is (major & minor).
3) When the **monitor** then notifies that there are no more beacons in the range, stop **ranging**.

All this to save battery, otherwise just use the **ranging**.

**Comment by alann-maulana** [comment]
> Would be good, but I think is a limitation of the underlying API.
> 
> Probably the correct approach is:
> 
> 1. activate **monitoring** to see if there are beacons with that UUID
> 2. when there is some beacon, activate the **ranging** to understand which beacon it is (major & minor).
> 3. When the **monitor** then notifies that there are no more beacons in the range, stop **ranging**.
> 
> All this to save battery, otherwise just use the **ranging**.

It's a nice solution too. But for us, we use region of beacon with format like `UUID#major#minor` then when it come to entering or exiting region, we can get the complete parameters of beacon by splitting region with `#`. Simple!
