### ISSUE TITLE
Provide default constructor to allow extend Beacon class

### ISSUE THREAD

**Issue by vladaman** [alann-maulana/flutter_beacon#5]
Great work!

Can you Please consider to add public constructor so we can extend Beacon class if needed?

**Comment by alann-maulana** [comment]
Hi @vladaman 

Nice suggestion, i will add it soon along with updating background monitoring for regions.

**Comment by alann-maulana** [comment]
Fix by [commit 43d44bf](https://github.com/alann-maulana/flutter_beacon/commit/4595a2cfeae4c3650c3d8b402639ab2f5f974e7a)
