### ISSUE TITLE
Only indentifier not working for IOS

### ISSUE THREAD

**Issue by newbieflutter** [alann-maulana/flutter_beacon#53]
Hi,
   I have used this same function for android and it works fine. But on IOS it seems not working. I never specified any UUID is cause I want to scan any UUID within the identifier: 'com.example.myDeviceRegion',      ? How to achieve that in IOS ?

  initScanBeacon() async {
    await flutterBeacon.initializeScanning;
    await checkAllRequirements();
    if (!authorizationStatusOk ||
        !locationServiceEnabled ||
        !bluetoothEnabled) {
      print('RETURNED, authorizationStatusOk=$authorizationStatusOk, '
          'locationServiceEnabled=$locationServiceEnabled, '
          'bluetoothEnabled=$bluetoothEnabled');
      return;
    }
    final regions = <Region>[
      Region(
        identifier: 'com.example.myDeviceRegion',       
      ),
    ];

    if (_streamRanging != null) {
      if (_streamRanging.isPaused) {
        _streamRanging.resume();
        return;
      }
    }

**Comment by fluff** [comment]
iOS requires you to specify a list of UUIDs to scan for. There is simply not a public API in the iOS SDK that allows scanning for "all" UUIDs. See also https://stackoverflow.com/questions/34450371/how-to-scan-available-beacons-in-my-region-ios

**Comment by dariocavada** [comment]
This plugin uses **CoreLocation** for beacon detection for iOS and this is the limitation. 
A list of of **UUIDs** to scan for is required.

https://developer.apple.com/documentation/corelocation/clbeacon
