### ISSUE TITLE
Unable to detect Android devices

### ISSUE THREAD

**Issue by huitingyeong** [alann-maulana/flutter_beacon#55]
Hi, I used the plugin and the example code provided.
My iOS device is able to detect other iOS device. Android can detect iOS devices.
But both iOS and Android are not able to detect Android devices.

Any idea why?

**Comment by dariocavada** [comment]
What is meant by "detect" other devices?
Has a beacon simulator been activated on other devices?
Can you indicate an example of the test you did and the versions of iOS and Android used?

I don't know if the requested functionality matches the functionality of this package which is to locate just **iBeacons**.

**Comment by AkshayNG** [comment]
The package is for detecting iBeacon only. So you need to turn your android device into iBeacon using :

if(Platform.isAndroid) {
      beaconBroadcast.setLayout('m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24')
          .setManufacturerId(0x004C);
}

where beaconBroadcast is an instance of [BeaconBroadcast]( https://pub.dev/packages/beacon_broadcast)

**Comment by jjakob666** [comment]
You could edit the FlutterBeaconPlugin.java to add support for Altbeacon and eddystone beacon like so:

> public static final String IBEACON_LAYOUT = "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24";
  public static final String ALTBEACON_LAYOUT = "m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25";
  public static final String EDDYSTONE_TLM_LAYOUT = "x,s:0-1=feaa,m:2-2=20,d:3-3,d:4-5,d:6-7,d:8-11,d:12-15";
  public static final String EDDYSTONE_UID_LAYOUT = "s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19";
  public static final String EDDYSTONE_URL_LAYOUT = "s:0-1=feaa,m:2-2=10,p:3-3:-41,i:4-21v";
  public static final String URI_BEACON_LAYOUT = "s:0-1=fed8,m:2-2=00,p:3-3:-41,i:4-21v";
  
  private final BeaconParser iBeaconLayout = new BeaconParser()
      .setBeaconLayout(IBEACON_LAYOUT);
  private final BeaconParser altBeaconLayout = new BeaconParser()
          .setBeaconLayout(ALTBEACON_LAYOUT);
  private final BeaconParser eddystoneBeaconLayout = new BeaconParser()
          .setBeaconLayout(EDDYSTONE_UID_LAYOUT);


    private void initialize() {
    beaconManager = BeaconManager.getInstanceForApplication(registrar.context());
    if (!beaconManager.getBeaconParsers().contains(iBeaconLayout)) {
      beaconManager.getBeaconParsers().clear();
      beaconManager.getBeaconParsers().add(iBeaconLayout);
      beaconManager.getBeaconParsers().add(altBeaconLayout);
      beaconManager.getBeaconParsers().add(eddystoneBeaconLayout);
    }
  }

**Comment by jjakob666** [comment]
> The package is for detecting iBeacon only. So you need to turn your android device into iBeacon using :
> 
> ```
> if(Platform.isAndroid) {
>       beaconBroadcast.setLayout('m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24')
>           .setManufacturerId(0x004C);
> }
> ```
> 
> where beaconBroadcast is an instance of [BeaconBroadcast](https://pub.dev/packages/beacon_broadcast)

This doesn't work on Android. Fails to broadcast the beacon.  The best is to fix flutter_beacon to accept and detect/range AltBeacons so it works with beacon_broadcast. See my post above for the fix

**Comment by AkshayNG** [comment]
> This doesn't work on Android. Fails to broadcast the beacon. The best is to fix flutter_beacon to accept and detect/range AltBeacons so it works with beacon_broadcast. See my post above for the fix

Not sure whats wrong, broadcasting is working fine my side. But I'll try out the solution you suggested. Also would it range the beacons in background for android 8.0+ ? I'm facing https://github.com/alann-maulana/flutter_beacon/issues/61. Please help @jjakob666

**Comment by jjakob666** [comment]
The two devices I have (Amazon FireHD tablet) and my samsung S9  don't have
an issue. no special code needed,  I switch to another app and the data
still comes in.

Regards,

Jason G Jakob
j.evolutia@gmail.com
Cel: 1- 519-841-8617

**Comment by jjakob666** [comment]
Also I run BeaconScope, and it can pickup the beacons coming from both my devices even when I'm playing video on both devices.

**Comment by AkshayNG** [comment]
> The two devices I have (Amazon FireHD tablet) and my samsung S9  don't have
an issue. no special code needed,  I switch to another app and the data
still comes in.

In my test, the beacons are being detected in background for just few minutes (not more than 5 min.), this is due to restrictions laid by android from version 8.0+.

**Comment by alann-maulana** [comment]
With latest update [flutter_beacon: 0.4.0](https://pub.dev/packages/flutter_beacon/versions/0.4.0) you can transmit as iBeacon too instead of scanning beacon only.
