### ISSUE TITLE
Background monitor in android

### ISSUE THREAD

**Issue by AlirezaDaryani** [alann-maulana/flutter_beacon#59]
Hi, i want get ibeacon uuid , major and minor when app killed.
Its work on ios so good and no problem there.
But, in android, app can not get data in monitor region method.
I tried to reopen app or resume ranging stream when monitor received data, but there is no data.

Any Help?

**Comment by is10vmust** [comment]
Hi @AlirezaDaryani i know i'm not benefit you i hope that , but can you please provide me the method you use it to run the app in IOS after killing the app  

and about android the only way after reads much articles is this lib. using native code :
https://altbeacon.github.io/android-beacon-library/documentation.html

 
many thanks 👍

**Comment by AlirezaDaryani** [comment]
Thanks for your response ,
Actually I’m working on native in android side.
In IOS side, i just use monitoring and ranging with location always permission, after get right beacon, show local notification.
there is no specific code for IOS.

**Comment by alann-maulana** [comment]
If any one of us can help me migrating this library #67 it would be greate :)
