### ISSUE TITLE
Missing macAddress in toJson method

### ISSUE THREAD

**Issue by vladaman** [alann-maulana/flutter_beacon#6]
Following method is missing macAddress field.

https://github.com/alann-maulana/flutter_beacon/blob/43d44bf605bca7ad6b9f6e5001bc79ba73a6830d/lib/beacon/beacon.dart#L114

**Comment by alann-maulana** [comment]
Hi @vladaman 

I'm little confused, because `CoreLocation` in iOS doesn't return mac address unlike in Android. Is it okay to adding mac address field within platform Android only? I will update it soon..

**Comment by alann-maulana** [comment]
Fix by [commit 43d44bf](https://github.com/alann-maulana/flutter_beacon/commit/4595a2cfeae4c3650c3d8b402639ab2f5f974e7a)
