### ISSUE TITLE
Scan beacon after killed the app iOS 

### ISSUE THREAD

**Issue by ammarmahafeza** [alann-maulana/flutter_beacon#60]
When I killed the app the app stop scan the beacon  how can solve this problem on iOS

**Comment by alann-maulana** [comment]
hi @ammarmahafeza 

We are doing a lot of research for overcoming these issue on iOS. But sorry, I can post the solution here. I'll give you a good starting point https://github.com/opentrace-community/opentrace-ios/issues/4

Hope this helps.
