### ISSUE TITLE
are this plugin support beacon accelerometer sensor ??

### ISSUE THREAD

**Issue by ammarmahafeza** [alann-maulana/flutter_beacon#62]
hello everyone after more than 3 months using this plugin and I thanks all who has develop it , I need to get the accelerometer xyz data are that possible and if i have an sdk with native how can I handle that with this plugin ....

thanks

**Comment by alann-maulana** [comment]
Hi @ammarmahafeza 

Currently I'm buliding this library for scanning beacon with iBeacon protocol only for both Android and iOS. If you intended to add new functionality it would be great :) 

Thanks
