### ISSUE TITLE
doesn't work on ios 13

### ISSUE THREAD

**Issue by j04ntoh** [alann-maulana/flutter_beacon#65]
managed to run on iphone but it stuck on loading screen.
Bluetooth icon enabled only when 1st installed.

**Comment by doggo4242** [comment]
same issue, problem appears to be requesting location permissions, however after implementing this in the sample, it was still stuck on the loading screen.

**Comment by danwood76** [comment]
Running the 0.3.0 release doesn't work on iOS13, however running the latest version from git does!

**Comment by doggo4242** [comment]
Thanks, that worked! I think this issue can be closed now.
