### ISSUE TITLE
how edit this github package code to do monitoring 

### ISSUE THREAD

**Issue by Emily-li1999** [alann-maulana/flutter_beacon#68]
how edit this github package code to do monitoring(I want to know whether enter or exist this beacon )in flutter?

**Comment by alann-maulana** [comment]
Hi @Emily-li1999 

There is already monitoring method for beacons https://github.com/alann-maulana/flutter_beacon#monitoring-beacons

If you intended to add other functionality to this little package, you can start by inspecting `ios` and `android` folder containing the native code.
