### ISSUE TITLE
Allow to customize scan period on Android

### ISSUE THREAD

**Issue by paolorotolo** [alann-maulana/flutter_beacon#76]
Hi! Thanks for your work.
AltBeacon, on which this plugin is based on for the Android part, allows developers to customize the duration of the bluetooth scan period.

This is done with the method `setForegroundScanPeriod(long p)`

It would be nice to expose this optional settings to the Flutter side, so the plugin could support more uses cases.

**Comment by alann-maulana** [comment]
Hi @paolorotolo 

Yeah it's a nice to have feature, I will take a look for it after finish up adding sound null safety checks.

Thanks.

**Comment by paolorotolo** [comment]
Nice, if you want ping me after null safety has landed. I can take care of updating the pull and resubmit.

**Comment by alann-maulana** [comment]
Yes it was https://github.com/alann-maulana/flutter_beacon/releases/tag/0.5.0

**Comment by paolorotolo** [comment]
@alann-maulana  Thanks, if I'm correct there's no need to update the pull. You're still able to merge it automatically and the code doesn't require updates to null safety.

**Comment by Marthijs-Berfelo** [comment]
@alann-maulana when is the next release expected?

**Comment by alann-maulana** [comment]
> @alann-maulana when is the next release expected?

Hi @Marthijs-Berfelo 

I'm still working on fixing beacon scanner not working on some device for both Android and iOS. This is related to newer OS version, updated permissions etc.

**Comment by dariocavada** [comment]
Hi @alann-maulana, if you need some testing or help for fixing bugs I can test on 2 android devices and iPhone 11, iPhone 7, 8 and 6.
