### ISSUE TITLE
Target file "lib\main.dart" not found.

### ISSUE THREAD

**Issue by PeterPoll** [alann-maulana/flutter_beacon#84]
Hello, how i should start run this project ? there is no main.dart file

**Comment by renoinn** [comment]
this project is package project for flutter. not exist "lib\main.dart".
you can run "example/lib/main.dart" to start example app.

**Comment by PeterPoll** [comment]
Ok, I have some beacons and I'm trying to find a simple project (app) where i can receiving notifications. Is this app for this reason?

Thank you!

**Comment by renoinn** [comment]
this is plugin project, not app. the plugin can detect beacons, but does not provide notification.
if you have Android, you can use "nRF Connect" app to detect beacons.
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=ja&gl=US

**Comment by PeterPoll** [comment]
Thank you. Now things is little more clear. 

So this app (on Android) is already exist to detect beacons ? 

Is there any way to create an app with flutter to detect beacons ?

**Comment by renoinn** [comment]
you can use flutter_beacon plugin for detect beacons in your flutter app.

**Comment by PeterPoll** [comment]
Do you know any demo of this ? 

I found 2 on github but I can't startet because they doesn't have also main.dart.

Bellow is the links of this 2 github demos. I think is for this reason beacuse using flutter_beacon. Confirm that please.
https://github.com/loup-v/beacons
https://github.com/alann-maulana/flutter_beacon

**Comment by alann-maulana** [comment]
Hi @PeterPoll 

You can run the example code provided on example folder here https://github.com/alann-maulana/flutter_beacon/tree/master/example. I have been updated it recently.

Hope this helps.
