### ISSUE TITLE
Ranging results always return beacons list with one Beacon

### ISSUE THREAD

**Issue by Rav-Naz** [alann-maulana/flutter_beacon#86]
Hello, I'm using flutter_beacon: ^0.3.0 version on real Android device. I have two iBeacon BLE devices, and both works. However, everytime when RangingResults occurs (1 second, btw. - can I scan more frequently?), in beacons list is always one of those iBeacons. In next scan, second is detected and is in result list. There is also scans where NO beacons is detected, even tho I do not moving beacons nor phone.

This is my Ranging code (from examples in pub.dev):
`_streamRanging =
        flutterBeacon.ranging(regions).listen((RangingResult result) {
            print(result);
          if (result != null && mounted) {
            setState(() {
              _regionBeacons[result.region] = result.beacons;
              _beacons.clear();
              _regionBeacons.values.forEach((list) {
                _beacons.addAll(list);
              });
              _beacons.sort(_compareParameters);
            });
          }
        });`

Thanks in advance for any help.

**Comment by PeterPoll** [comment]
Hello! 

I'm trying but detecting 0 beacons, can you help me how to make it works ? I have 1 beacon device from blueup beacons. 

Please, I'm looking 2 months now for this solutions.

Thank you very much!

**Comment by Rav-Naz** [comment]
Hello, I'm done the same like in [example](https://pub.dev/packages/flutter_beacon/example). Only thing I've changed is:
`final regions = <Region>[
      Region(
        identifier: 'Cubeacon',
        proximityUUID: 'CB10023F-A318-3394-4199-A8730C7C1AEC',
      ),
    ];`
to:
`final regions = <Region>[
      Region(
        identifier: 'myCustomName',
        proximityUUID: 'myPromixityUUID', //it will be like in this pattern xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, you could find this uuid by scanning beacons with other app from google play, e.g Locate Beacon by Radius Network, Inc.
      ),
    ];`

**Comment by PeterPoll** [comment]
I have tried but isn't work. 

So the only change that I should make is the promixityUUID? 

Am I right ?

Thank you.

**Comment by Rav-Naz** [comment]
Sure, I haven't changed more.

**Comment by PeterPoll** [comment]
Ok maybe need specific configuration from the beacon side ? 

I have blue up beacon. https://www.blueupbeacons.com/index.php?page=mini

I have an app from this company and I can edit the configuration also I can see UUID to add it on my code.

I will try it again, I hope it works.. If you have more advices for this please tell me, I'm looking weeks for this to work.

Thank you.

**Comment by alann-maulana** [comment]
For Android scanning, you can at least add an `identifier` only for region scanning. But, on iOS we need at least `identifier ` and `proximityUUID ` to make it working. You can check the latest example here https://github.com/alann-maulana/flutter_beacon/tree/master/example

Close it for now

**Comment by PeterPoll** [comment]
Thank you very much! I will try it again the example you just updated.

Thank you!

**Comment by anilkumar91583** [comment]
Not able to scan iBeacons, trying from a long time in the result it is empty. Can any one help me out
