### ISSUE TITLE
Wondering if there is an ETA on updating the pub.dev package

### ISSUE THREAD

**Issue by BrayFlex** [alann-maulana/flutter_beacon#87]
I can't use direct links to github in my project, is there a timelime to update the pub.dev package?

**Comment by alann-maulana** [comment]
Hi @BrayFlex 

Sorry, I have been working on some projects recently, just publishing it yesterday on pub.dev

You can check here [flutter_beacon: ^0.4.0](https://pub.dev/packages/flutter_beacon/versions/0.4.0)
