### ISSUE TITLE
Monitoring does not work on iOS

### ISSUE THREAD

**Issue by EricHier** [alann-maulana/flutter_beacon#96]
Hi there! 

When testing the [example project](https://github.com/AppHoc/beacons-test) I created, the monitoring does not work on iOS. The Android version is working fine. I am sure that the beacon with the specified `uuid` is in range (detected in other apps and on a mac) and the permission `when in use` is granted correctly. Bluetooth is enabled. 

What can be the reason the plugin is not working for me? I highly appreciate your help!

**Comment by Bhuvan69** [comment]
@EricHier Did you make it work? Any update on this?

**Comment by EricHier** [comment]
@Bhuvan69 I did not find a solution and stopped working with the plugin. :/

**Comment by Bhuvan69** [comment]
@EricHier Any other plugin which does this?
